source 'https://rubygems.org'
gem 'dotenv-rails', groups: [:development, :test]
gem 'rails', '4.1.1'
gem 'pg'
gem 'sass-rails', '~> 4.0.3'
gem "font-awesome-sass-rails"
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',   group: :doc
gem 'high_voltage'
gem 'bootstrap-sass'
gem 'autoprefixer-rails'
gem 'paperclip'
gem 'masonry-rails'
gem 'monban-generators'
gem 'simple_form'
gem 'aws-s3'
gem 'aws-sdk'
gem 'will_paginate'
gem 'rails_admin'
gem 'stripe'
gem 'bootstrap_form'
